[functions.create-stripe-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.refresh-whatsapp-token]
verify_jwt = false
[functions.subscribe-newsletter]
enabled = true
verify_jwt = true
import_map = "./functions/subscribe-newsletter/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/subscribe-newsletter/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/subscribe-newsletter/*.html" ]
